### ISSUE TITLE
Ideas for future of Open Source Ladies meetup

### ISSUE THREAD

**Issue by Incabell** [opensourcediversity/opensourcediversity.org#1]
At the meetup (02.05.18) we (@jancborchardt @sleepypioneer @suntala and I) collected some ideas of what we want to make of the meetup, and how to go about it. Not everything here needs to happen that way and nothing is set in stone, but I think it's a good idea to write what was said down and be able to point to it and talk about it more.

- have topics for each meetup, focus on working on a specific project
  - Wikipedia, OpenStreetMap, Nextcloud, Wikidata, Fedora, GitLab, Mozilla, Bahmni, Discourse, … 
  - non-code contributions like editing Wikipedia or OpenStreetMap, design, writing documentation, translation etc.
  - other projects from e.g. RailsGirls summer of code or Outreachy
  - Projects directly concerned with diversity: Speakerinnen, Diversitytickets, Open Source Diversity website, Bl00dyHealth, WheelMap, Co-lab by Arati, SignDict, …
  - Big projects but also smaller, quicker-to-get-involved ones
- Maybe even 2 times in a row because first time might be needed for setup
- Could be about host company (Wikimedia, Nextcloud, …)
- Help projects add Code of Conduct, good first issues, …
- Do another hackathon day!
- rename Open Source Ladies to »Open Source Diversity Berlin«?
- Workshop through OpenTechSchool on how to contribute to open source
- partnerships with language-specific meetups like PyLadies, RailsGirls/code_curious
- aggregate articles and events on website
- STICKERS & tshirts!
- Open Source Diversity Summit
- Talk at more conferences

**Comment by GretaD** [comment]
Hello everyone,

And thank you for publishing the notes. 
Those are very points to start. I like the point "Help projects add Code of Conduct, good first issues", this is a good one, but i would suggest also to create/adapt one for diversity events publish it here or at webiste and just share it with an event that doesn't have one, or have not a good one. I'd add also, safe and security information/instructions. Specially for international events.

I also like the idea of removing the word ' ladies' from the name of the project, since that makes it a bit exclusive. And I'm fine with the name proposed.

"have topics for each meetup"- this definitely can help the meeting to be more productive. Maybe we can do a survey and see what people would like to do or in what project they would like to work on. So with that we can 'measure' the level of participants and be prepared to help with whats needed.

**Comment by camilasan** [comment]
+1 to rename to »Open Source Diversity Berlin«

**Comment by jancborchardt** [comment]
We just renamed the meetup :)
- https://twitter.com/opensrcladies/status/1001532973047480326
- https://www.meetup.com/opensourcediversity/

We also talked about a possible structure for each meetup which will be the same no matter which project we work on. The notes are added to the wiki at: https://github.com/opensourcediversity/opensourcediversity.org/wiki/Meetup-agenda-template

**Comment by jancborchardt** [comment]
Just saw [this tweet](https://twitter.com/bl00dymarie/status/1002138768185483265) on @bl00dymarie talking about https://bloodyhealth.gitlab.io/en/

Since we want to work on one specific project at each of the meetups, Bloody Health seems to be a great candidate for one of our next meetups! :) I think at the next one we wanted to work on https://opensourcediversity.org one more time, but woud you be up for joining one of the meetups after that @bl00dymarie? https://www.meetup.com/opensourcediversity/

We have a draft of recommended prerequisites and rough timeline at the meetup at https://github.com/opensourcediversity/opensourcediversity.org/wiki/Meetup-agenda-template – also let us know if that works, or if you have suggestions! :)

**Comment by jonatoni** [comment]
@Incabell thanks for sharing the notes :) I just want to add a few things:

- Another open source project that can be included as a topic is Fedora Project. I'm part of this community and I can try to find someone that lives in Berlin to join your meetups and give a talk about the community, how to contribute etc. In August I will be in Berlin, so if you will have events during August I would be more than happy to talk about Fedora.
- Aggregate articles and events on the website -> we should document all the activities we do, with some info about the event and photos - is very important to do this and share with others the work we have done
- STICKERS & t-shirts! - I love this idea, especially stickers - because you can give stickers to people we meet at different events and conferences to spread the word about Open Source Diversity
- Open Source Diversity Summit - last year I was discussing this with @kristiprogri because we don't know any conference like this and would be great to have one. If we have a group of people willing to organize it would be awesome. We are +1 to organize it.
- Talk at more conferences - we are already doing it and it's great to spread the word about Open Source Diversity in this way :)

**Comment by lwasser** [comment]
👋 hi there! i see this issue is a  few  years old but i wanted to say hello  and potentially connect with this group. I'm working on a project called [pyOpenSci](https://www.pyopensci.org) - modeled  after ropensci that's all about building well documented, tested and discoverable software for science. I want a core goal of this effort to be about diversity (this is not on the website now but will be). i've reached out to pyladies already but i'm interesting in chatting with those involved in this effort to see if there are places we could connect.
  
Id like to see our effort support training and mentorship for Python OSS and i'm in the process of writing a proposal for it as well. All the best!

**Comment by jwflory** [comment]
Hi all, I am cleaning up and triaging some old issues to figure out where we are on website development in 2021. I am closing this issue as we get back up to speed on the current backlog on the site. 🎬
