### ISSUE TITLE
Add a section for Women Centric scholarships offered by various companies.

### ISSUE THREAD

**Issue by asquare14** [opensourcediversity/opensourcediversity.org#50]
- Women Techmakers Google
- Adobe Women in Research
- Toptal
- Nutanix
- GHC
- Western Digital
- Adobe Women In Tech India
- WeTech Qualcomm Scholar
- Goldman Sachs Scholarship
- Juniper Network Scholarships
- Acumen Scholarship
- Snap Scholarship
- Digital Product School
- Red Hat Open Source Contributor
 Also add links to pages .

**Comment by jancborchardt** [comment]
Since we specifically want to focus on _open source_ and not only "tech" in general, the only relevant one for us seems to be **Red Hat Open Source Contributor**? I couldn’t find any further info on that though. We do already list the Red Hat "Women in Open Source Award". :)

What does everyone think?

**Comment by aSquare14** [comment]
Sounds good to me !

**Comment by sara-02** [comment]
Does O'Reilly's OSCON Open Source Awards count? They are open to individuals and organizations(not limited to women)
Ref: https://en.wikipedia.org/wiki/O%27Reilly_Open_Source_Award

**Comment by jancborchardt** [comment]
> Does O'Reilly's OSCON Open Source Awards count? They are open to individuals and organizations(not limited to women)
> Ref: https://en.wikipedia.org/wiki/O%27Reilly_Open_Source_Award

Good question – I would tend to say no since it’s a generic award not specific to underrepresented groups, even though they seemingly improved through the years regarding diversity.
That is, if we add this one then there are _a lot_ of projects that will be on the website. :D Just like also all hackerspaces are potentially open to everyone, but in practice it’s a bit different.

What does everyone else think? @sleepypioneer @emmairwin @jonatoni @alicetragedy and others?

**Comment by alicetragedy** [comment]
Yep, I agree with @jancborchardt — I don't feel that O'Reilly's OSCON Open Source Awards counts given it's not focused on promoting or supporting diversity in open source software.

**Comment by jonatoni** [comment]
I am closing this issue as stale.
