### ISSUE TITLE
Add a section saying who all maintainers of this website.

### ISSUE THREAD

**Issue by asquare14** [opensourcediversity/opensourcediversity.org#51]
A small photo with a short description and email. In case, anyone has questions they can message us.

**Comment by nitink4472** [comment]
I would like to work on this issue but tell me as i'm a newcomer that, Are maintainers the same as contributors/backers?

**Comment by jancborchardt** [comment]
Since contributing to Open Source Diversity can have many different means, lots of which will not necessarily mean doing a lot on the website, I’d prefer if we don’t list specific people as maintainers. :) Open Source Diversity is meant as a hub by and for people working to push inclusion & diversity in open source rather than a specific group or project.

(We already do this to a certain extent in the readme of this repository with the "backers" widget from Open Collective: https://github.com/opensourcediversity/opensourcediversity.org#-contributors-backers--sponsors )

What does everyone think? @sleepypioneer @princiya @alicetragedy @Haimchen & others

**Comment by alicetragedy** [comment]
Sooo I think both perspectives are valid. I definitely think that adding people as “maintainers” can a) put a lot of responsibility (potentially unwanted) on certain folks and b) lead to forgetting people who also played a big part. 
I also agree that contributing and maintaining a group isn’t always visible work (or the type of work we assume when we call someone a “maintainer”). 

I do think it might be useful though to have a few people listed either on the site or on the repo, particularly in the context of looking into Code of Conduct violations and enforcing the Code of Conduct for our community. However maybe this is part of a bigger conversation? Don’t know how y'all feel about this.

**Comment by Shu12388y** [comment]
@asquare14 can you assign this issue to me

**Comment by Shu12388y** [comment]
@jancborchardt can you assign this issue to me

**Comment by jonatoni** [comment]
I do agree we are missing some governance for OSD - but for now I would keep it as it is because we don't have the capacity for it. Whenever we feel ready and have someone to lead the efforts for creating some governance we can always come back to this discussion. For now I'm closing the issue as stale.
